[microtik]
address = "192.168.1.1"
port = 8728
username ="admin"
password ="admin"

[web]
address = "localhost"
port = 6566

[ping]
address = ["google.de", "cnn.com"]
json = false

[mf823]
address = "192.168.3.1"
# parameters = ["lte_rsrp","modem_main_state", "pin_status", "loginfo", "new_version_state", "current_upgrade_state", "is_mandatory", "signalbar", "network_type", "network_provider", "ppp_status", "EX_SSID1", "sta_ip_status", "EX_wifi_profile", "m_ssid_enable", "RadioOff", "simcard_roam", "lan_ipaddr", "station_mac", "battery_charging", "battery_vol_percent", "battery_pers","spn_display_flag","plmn_display_flag","spn_name_data","spn_b1_flag","spn_b2_flag","realtime_tx_bytes","realtime_rx_bytes","realtime_time","realtime_tx_thrpt","realtime_rx_thrpt","monthly_rx_bytes","monthly_tx_bytes","monthly_time","date_month","data_volume_limit_switch","data_volume_limit_size","data_volume_alert_percent","data_volume_limit_unit","roam_setting_option","upg_roam_switch","ap_station_mode","sms_received_flag","sts_received_flag","sms_unread_num"]
parameters = ["lte_rsrp", "network_type", "ppp_status", "network_provider", "signalbar", "realtime_rx_bytes", "realtime_tx_bytes", "monthly_rx_bytes", "monthly_tx_bytes", "realtime_rx_thrpt", "realtime_tx_thrpt", "realtime_time"]
json = false